# Generated by Django 5.0.7 on 2024-12-09 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='models_auto',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле может содержать только буквы русского и английского алфавита, точки и дефисы.', regex='^[a-zA-Zа-яА-ЯёЁ.\\-]+$')], verbose_name='Модель автомобиля'),
        ),
    ]
