# Generated by Django 5.0.7 on 2024-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='users/default_user_image.jpg', upload_to='users/$Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
