# Generated by Django 5.0.7 on 2024-11-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='users/$Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
