# Generated by Django 5.0.7 on 2024-08-17 17:13

import bestcar.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestcar', '0003_alter_publishing_a_trip_author_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='отправление')),
                ('arrival', models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='прибытие')),
                ('departure_time', models.DateTimeField(validators=[bestcar.validators.Validators_date_model()], verbose_name='время отправления')),
                ('arrival_time', models.DateTimeField(default=None, validators=[bestcar.validators.Validators_date_model()], verbose_name='время прибытия')),
                ('seating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='количество мест')),
                ('price', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autho', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bestcar.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'зарезервированные поездки',
                'verbose_name_plural': 'зарезервированные поездки',
            },
        ),
    ]
