# Generated by Django 5.0.7 on 2024-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'зарезервированная поездка',
                'verbose_name_plural': 'зарезервированные поездки',
            },
        ),
    ]
