# Generated by Django 5.0.7 on 2024-12-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestcar', '0002_initial'),
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='author_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_trip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bestcar.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='booking',
            name='name_companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пассажира'),
        ),
    ]
