# Generated by Django 5.0.7 on 2024-12-09 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'зарезервированная поездка', 'verbose_name_plural': 'зарезервированные поездки'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только русские буквы и символы \\-,./.', regex='^[а-яА-ЯёЁ0-9\\-,./ ]+$')], verbose_name='прибытие'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только русские буквы и символы \\-,./.', regex='^[а-яА-ЯёЁ0-9\\-,./ ]+$')], verbose_name='отправление'),
        ),
    ]
