# Generated by Django 5.0.7 on 2024-12-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0003_alter_publishing_a_trip_arrival_and_more'),
        ('booking', '0003_alter_booking_options_alter_booking_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='author_trip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bestcar.publishing_a_trip'),
            preserve_default=False,
        ),
    ]
