# Generated by Django 5.0.7 on 2024-08-18 18:28

import bestcar.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Publishing_a_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='отправление')),
                ('arrival', models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='прибытие')),
                ('departure_time', models.DateTimeField(validators=[bestcar.validators.Validators_date_model()], verbose_name='время отправления')),
                ('arrival_time', models.DateTimeField(default=None, validators=[bestcar.validators.Validators_date_model()], verbose_name='время прибытия')),
                ('free_seating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='количество мест')),
                ('reserved_seats', models.PositiveIntegerField(default=0, verbose_name='количество бронированных мест')),
                ('price', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('models_auto', models.CharField(max_length=100, verbose_name='модель автомобиля')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bestcar.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Опубликованные поездки',
                'verbose_name_plural': 'Опубликованные поездки',
                'ordering': ('departure_time',),
            },
        ),
    ]
