# Generated by Django 5.0.7 on 2024-12-08 16:51

import bestcar.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='arrival',
            field=models.CharField(help_text='Город или место прибытия.', max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='прибытие'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='arrival_time',
            field=models.DateTimeField(default=None, help_text='Дата и время окончания поездки.', validators=[bestcar.validators.Validators_date_model()], verbose_name='время прибытия'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='author',
            field=models.ForeignKey(default=None, help_text='Пользователь, который создал поездку.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='departure',
            field=models.CharField(help_text='Город или место отправления.', max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='отправление'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='departure_time',
            field=models.DateTimeField(help_text='Дата и время начала поездки.', validators=[bestcar.validators.Validators_date_model()], verbose_name='время отправления'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='free_seating',
            field=models.PositiveSmallIntegerField(default=1, help_text='Общее количество свободных мест.', verbose_name='количество мест'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='Стоимость поездки в условных единицах.', verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='reserved_seats',
            field=models.PositiveIntegerField(default=0, help_text='Количество уже забронированных мест.', verbose_name='количество бронированных мест'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор поездки (генерируется автоматически).', max_length=100, unique=True),
        ),
    ]
