# Generated by Django 5.0.7 on 2024-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='free_seating',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='количество мест'),
        ),
    ]
