# Generated by Django 5.0.7 on 2024-09-17 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0004_alter_publishing_a_trip_free_seating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publishing_a_trip',
            index=models.Index(fields=['departure', 'arrival', 'free_seating', 'departure_time'], name='trip_filter_idx'),
        ),
    ]
