# Generated by Django 5.0.7 on 2024-12-08 17:08

import bestcar.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0004_alter_publishing_a_trip_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='arrival',
            field=models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='прибытие'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='arrival_time',
            field=models.DateTimeField(default=None, validators=[bestcar.validators.Validators_date_model()], verbose_name='время прибытия'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='departure',
            field=models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='отправление'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='departure_time',
            field=models.DateTimeField(validators=[bestcar.validators.Validators_date_model()], verbose_name='время отправления'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='free_seating',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='количество мест'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='reserved_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='количество бронированных мест'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
