# Generated by Django 5.0.7 on 2024-09-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0005_publishing_a_trip_trip_filter_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing_a_trip',
            name='cat',
        ),
    ]
