# Generated by Django 5.0.7 on 2024-12-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0005_alter_publishing_a_trip_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publishing_a_trip',
            name='trip_filter_idx',
        ),
    ]
