# Generated by Django 5.0.7 on 2024-09-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0006_remove_publishing_a_trip_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='free_seating',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='количество мест'),
        ),
    ]
