# Generated by Django 5.0.7 on 2024-09-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0007_alter_publishing_a_trip_free_seating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing_a_trip',
            name='models_auto',
        ),
    ]
